### ISSUE TITLE
 Bug/Improvement (Reddit): Some links still have out.reddit.com tracking redirection

### ISSUE THREAD

**Issue by i486** [inotia00/ReVanced_Extended#1961]
### Type

Error at runtime

### Tools used

Revancify

### Application

Reddit Official Android application v2024.12.0+

### Bug description

**Description:**
When clicking on the thumbnail, I'm experiencing a redirection issue where the link opens up on out.reddit.com instead of directly opening actual link in the browser.

**Steps to Reproduce:**

    Go to https://www.reddit.com/r/DeepIntoYouTube/
    Open any YouTube link from the subreddit.

**Expected Behavior:**
The destination link should open directly in the browser or apps.

**Actual Behavior:**
Clicking on the thumbnail results in a redirection to out.reddit.com

**Screenshots**
<a href="url"><img src="https://github.com/YT-Advanced/ReX-patches/assets/625325/8f196d05-7427-4390-ba9f-ef2c252a0fba" align="left" height="480" ></a>

<a href="url"><img src="https://github.com/YT-Advanced/ReX-patches/assets/625325/a7d10feb-ef94-4a1e-a0f4-f8737059b79b" height="480" ></a>

**Additional information**
This issue happens despite **open-links-directly** and **open-links-externally** are enabled in RVX settings.

**More info**
https://www.reddit.com/r/redditmobile/search/?q=out.reddit.com&include_over_18=on&restrict_sr=on&t=all&sort=relevance
https://www.reddit.com/r/beta/comments/t8fuza/if_i_had_a_dollar_for_every_second_spent_in/
https://www.reddit.com/r/redditmobile/comments/y3a1ql/android_2022380_open_web_links_in_external/
https://www.reddit.com/r/revancedapp/comments/zahhqd/if_possible_please_make_a_patch_to_disable_this/
https://www.reddit.com/r/bugs/comments/ym96ia/reddit_app_doesnt_open_links_on_external_browser/
https://www.reddit.com/r/help/comments/z3lrv6/reddit_app_wont_open_web_links_in_external/

### Device Environment

Android 11

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.
