### ISSUE TITLE
suggestion: TODO list for ARSCLib

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#2191]
### Application

Other

### Suggestion description

The `arsclib-old` branch has been created in the [revanced-patcher](https://github.com/inotia00/revanced-patcher/tree/arsclib-old), [revanced-cli](https://github.com/inotia00/revanced-cli/tree/arsclib-old), and [revanced-patches](https://github.com/inotia00/revanced-patches/tree/arsclib-old) repositories.

The [revanced-cli](https://github.com/inotia00/revanced-cli/releases/tag/v2.21.2-arsclib), [revanced-patches](https://github.com/inotia00/revanced-patches/releases/tag/v2.175.1-arsclib) repositories have Pre-Releases for the arsclib-old branch.

Pre-Releases are uploaded without separation of `dev` and `arslib-old` branches, which may confuse those who are downloading packages or looking for release notes.

The best way is to migrate a repository with Releases to a new repository.
(e.g. revanced-cli-arsclib, revanced-patches-arsclib)

### TODO

- [x] Create repositories `revanced-cli-arsclib` and `revanced-patches-arsclib` and migrate code.
- [x] Publish revanced-patcher (arsclib) to maven central. (for gh workflow)
- [ ] Add support for ARSCLib to rvx-builder.

**Comment by inotia00** [comment]
reflected in [rvx-builder-3.14.1](https://github.com/inotia00/rvx-builder/releases/tag/v3.14.1)
