### ISSUE TITLE
bug(YouTube/SponsorBlock): Can't disable Skip count tracking

### ISSUE THREAD

**Issue by Oleepre** [inotia00/ReVanced_Extended#2272]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.10.2

### Bug description

 In the Sponsorblock settings **Stats** section the skipped segments counter keeps going up even if that setting is off.

 
![Sponsi](https://github.com/user-attachments/assets/c45adf96-3a8f-4161-bdf3-00c47e3360cd)

 To reproduce:
 1_ Go to Revanced Extended Settings - > SponsorBlock
 2_ In the General Section turn off "_Enable Skip count tracking_".
 3_ Go to a video with sponsorblock segments and skip them/let them be skipped automatically.
 4_ Go back to SponsorBlock Settings -> Stats and see the **Skipped segments counter** went up.

### Additional context

 Turning the setting On or Off doesn't make a difference, neither does restarting the app or force closing it after changing it.

### Device Environment

Android 14, Galaxy A32

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
That setting is for whether to send the skip counter to the SponsorBlock server

Even if that setting is turned off, the skip counter is still recorded locally (in app data)
